#!/usr/bin/env node
/**
 * Seed office_activity_journal table with Government 37 ministerial activity data.
 *
 * Populates comprehensive timeline of all ministry changes, appointments,
 * reforms, and major policy initiatives from December 2022 through 2026.
 *
 * Usage:
 *   npm run db:seed-activity-journal
 */

import Database from 'better-sqlite3';
import path from 'path';

const DB_PATH = path.join(process.cwd(), 'knesset.db');

interface ActivityEntry {
  canonicalOfficeId: number;
  activityDate: string;
  activityType: string;
  activityTitle: string;
  description: string;
  affectedPersonName: string | null;
  affectedPersonId: number | null;
  governmentNum: number;
  coalitionParty: string | null;
  durationDays: number | null;
  budgetAllocation: number | null;
  controversyLevel: 'none' | 'minor' | 'moderate' | 'major';
  policyFocus: string | null;
  notes: string;
  hebrewNotes: string | null;
  dataSource: string;
  sourceUrl: string | null;
  confidenceLevel: number;
}

// All Government 37 ministerial activities (Dec 2022 - Apr 2026)
const activities: ActivityEntry[] = [
  // MINISTRY OF FINANCE
  {
    canonicalOfficeId: 1, // finance
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Bezalel Smotrich appointed Finance Minister',
    description: 'Bezalel Smotrich (Religious Zionism) appointed as Minister of Finance with unprecedented expanded powers including West Bank settlement administration oversight.',
    affectedPersonName: 'בצלאל סמוטריץ\'',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Religious Zionism',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Finance, West Bank',
    notes: 'Largest portfolio expansion in finance ministry history; gained control of settlement development.',
    hebrewNotes: 'הרחבה חסרת תקדים של סמכויות; שליטה בתשתיות התנחלות',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%9E%D7%A9%D7%9C%D7%AA_%D7%99%D7%A9%D7%A8%D7%90%D7%9C_%D7%94%D7%A9%D7%9C%D7%95%D7%A9%D7%99%D7%9D_%D7%95%D7%A9%D7%91%D7%A2',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 1,
    activityDate: '2023-01-15',
    activityType: 'policy_launch',
    activityTitle: 'Tax abolition on disposables and sugary drinks',
    description: 'Smotrich eliminated tax on disposable dishware and sugary drinks as part of fiscal policy changes.',
    affectedPersonName: 'בצלאל סמוטריץ\'',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Religious Zionism',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Tax policy',
    notes: 'Early tax reforms; aimed at public consumption patterns.',
    hebrewNotes: 'ביטול מסים על פריטי חד-פעמיים ומשקאות סוכריים',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 1,
    activityDate: '2023-02-15',
    activityType: 'expansion',
    activityTitle: 'West Bank settlement administration authority granted',
    description: 'Ministry expanded to include governance of West Bank settlements; unified administration with Israeli territory operations.',
    affectedPersonName: 'בצלאל סמוטריץ\'',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Religious Zionism',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Settlements, West Bank',
    notes: 'Unprecedented transfer of settlement authority to finance minister; international controversy.',
    hebrewNotes: 'העברה של ניהול התנחלויות למשרד האוצר',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 1,
    activityDate: '2023-05-24',
    activityType: 'budget_allocation',
    activityTitle: 'Multi-year budget approval (2023-2024)',
    description: 'Knesset approved comprehensive state budget covering 2023-2024 with expanded security spending and welfare programs.',
    affectedPersonName: 'בצלאל סמוטריץ\'',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Religious Zionism',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Budget, Multi-year planning',
    notes: 'Included expansion laws for family welfare credit and education subsidies.',
    hebrewNotes: 'אישור תקציב רב-שנתי עם הרחבת התקציבים הביטחוניים',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 1,
    activityDate: '2023-09-11',
    activityType: 'policy_launch',
    activityTitle: 'Carbon tax implementation planned (2025-2030)',
    description: 'Knesset Finance Committee approved Smotrich\'s proposal for gradual carbon tax implementation on non-transportation fuels from 2025-2030.',
    affectedPersonName: 'בצלאל סמוטריץ\'',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Religious Zionism',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Environmental, Tax',
    notes: 'Long-term environmental policy; phased implementation over 5 years.',
    hebrewNotes: 'מס פחמן הדרגתי על דלקים שאינם תחבורה',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 90,
  },
  {
    canonicalOfficeId: 1,
    activityDate: '2023-04-15',
    activityType: 'controversy',
    activityTitle: 'Moody\'s credit rating downgrade',
    description: 'Credit rating agency Moody\'s downgraded Israel\'s rating outlook from "positive" to "stable" citing institutional concerns related to judicial reform.',
    affectedPersonName: 'בצלאל סמוטריץ\'',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Religious Zionism',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Credit, Fiscal health',
    notes: 'Direct connection to judicial reform; affects government borrowing costs.',
    hebrewNotes: 'הורדת דירוג של צפיית מודיס בעקבות הרפורמה המשפטית',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 95,
  },

  // MINISTRY OF JUSTICE
  {
    canonicalOfficeId: 2, // justice
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Yariv Levin appointed Deputy PM and Justice Minister',
    description: 'Yariv Levin (Likud) appointed as Deputy Prime Minister and Minister of Justice; appointed to lead comprehensive judicial reform initiative.',
    affectedPersonName: 'יריב לוין',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Judicial reform, Justice',
    notes: 'Key position; responsible for most controversial government initiative of the term.',
    hebrewNotes: 'מינוי לשר משפטים וסגן ראש הממשלה; מנהיג הרפורמה המשפטית',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%94%D7%A8%D7%A4%D7%95%D7%A8%D7%9E%D7%94_%D7%94%D7%9E%D7%A9%D7%A4%D7%98%D7%99%D7%AA_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C_(2023)',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 2,
    activityDate: '2023-01-04',
    activityType: 'reform',
    activityTitle: 'Judicial overhaul proposal announced',
    description: 'Yariv Levin and Simcha Rothman unveiled comprehensive judicial reform plan including: 61-vote Knesset override clause, government control of judge appointments, weakening Supreme Court authority.',
    affectedPersonName: 'יריב לוין',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Judicial system, Separation of powers',
    notes: 'Most contentious government initiative; sparked 10-month protest movement.',
    hebrewNotes: 'הצעת חוק דרמטית לשינוי מערכת המשפט; שינוי אתו של בחירת שופטים',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%94%D7%A8%D7%A4%D7%95%D7%A8%D7%9E%D7%94_%D7%94%D7%9E%D7%A9%D7%A4%D7%98%D7%99%D7%AA_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C_(2023)',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 2,
    activityDate: '2023-02-03',
    activityType: 'controversy',
    activityTitle: 'IDI poll shows public opposition (43% vs 31%)',
    description: 'Israel Democracy Institute published Voice Index poll showing 43% view judicial reform as "quite bad/very bad" vs 31% "quite good/very good"; indication of sharp public divide.',
    affectedPersonName: 'יריב לוין',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Public opinion, Judicial reform',
    notes: 'Majority disapproval evident from early polls; continued throughout reform period.',
    hebrewNotes: 'סקר הדעות הציבור מראה התנגדות רחבה לרפורמה',
    dataSource: 'idi',
    sourceUrl: 'https://www.idi.org.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 2,
    activityDate: '2023-01-10',
    activityType: 'controversy',
    activityTitle: 'Personal motivation: prosecution concerns alleged',
    description: 'Confidential reports indicate Levin accelerated judicial reform timeline partly due to personal concerns about potential prosecution by state prosecution service.',
    affectedPersonName: 'יריב לוין',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Personal interest, Judicial reform',
    notes: 'Alleged that Levin stated "prosecution will fabricate a case to deter us"; raises conflict of interest concerns.',
    hebrewNotes: 'חשדות שלוין מאיץ את הרפורמה בגלל קשיים משפטיים אישיים',
    dataSource: 'jdn',
    sourceUrl: 'https://www.jdn.co.il',
    confidenceLevel: 75,
  },
  {
    canonicalOfficeId: 2,
    activityDate: '2023-01-15',
    activityType: 'controversy',
    activityTitle: 'Mass protests begin (10-month campaign)',
    description: 'Start of large-scale public protests against judicial reform; demonstrations continue for 10 months across Israel.',
    affectedPersonName: 'יריב לוין',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: 300,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Public resistance, Democracy',
    notes: 'Unprecedented sustained protest movement; includes strikes, road blockades, reservist refusals.',
    hebrewNotes: 'התחזוקה של מחאה ציבורית ענקית למשך 10 חודשים',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%94%D7%A8%D7%A4%D7%95%D7%A8%D7%9E%D7%94_%D7%94%D7%9E%D7%A9%D7%A4%D7%98%D7%99%D7%AA_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C_(2023)',
    confidenceLevel: 100,
  },

  // MINISTRY OF NATIONAL SECURITY
  {
    canonicalOfficeId: 3, // national security
    activityDate: '2022-12-29',
    activityType: 'portfolio_transfer',
    activityTitle: 'Ministry renamed from Public Security to National Security',
    description: 'Portfolio renamed and restructured to emphasize expanded national security mandate; given unprecedented police and border control powers.',
    affectedPersonName: null,
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: null,
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Security, Police authority',
    notes: 'Structural change reflects expanded scope; Itamar Ben-Gvir given new authorities.',
    hebrewNotes: 'שם המשרד השתנה להדגיש את היבט הביטחון הלאומי',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%95%D7%95%D7%96%D7%91%D7%99%D7%98%D7%97%D7%95%D7%9F_%D7%9C%D7%A0%D7%99%D7%93%D7%A0%D7%99%D7%99%D7%D7%9C%D7%99',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 3,
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Itamar Ben-Gvir appointed Minister of National Security',
    description: 'Itamar Ben-Gvir (Jewish Power) appointed with expanded powers: policy-setting authority over Israel Police, control of Border Police in West Bank, settlement security responsibilities.',
    affectedPersonName: 'איתמר בן גביר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power (Otzma Yehudit)',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Police, Security, Settlements',
    notes: 'Most controversial ministerial appointment; unprecedented police control granted to far-right minister.',
    hebrewNotes: 'מינוי השר בן גביר עם סמכויות משטרה חסרות תקדים',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%A0%D7%99%D7%93_%D7%A9%D7%98%D7%97%D7%99%D7%9D_%D7%97%D7%93%D7%A9%D7%95%D7%AA',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 3,
    activityDate: '2023-01-03',
    activityType: 'controversy',
    activityTitle: 'Ben-Gvir Temple Mount visit sparks international crisis',
    description: 'Minister visited Temple Mount/Haram al-Sharif on January 3, 2023; sparked immediate international criticism from US, EU, and Arab states including Jordan, Egypt, Saudi Arabia, UAE.',
    affectedPersonName: 'איתמר בן גביר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'International relations, Religious sites',
    notes: 'Visit perceived as provocation to Muslim and Arab states; threatened regional stability.',
    hebrewNotes: 'ביקור משנוי במקום בעל משמעות דתית גדולה; מעורר התנגדות בינלאומית',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%90%D7%99%D7%AA%D7%9E%D7%A8_%D7%91%D7%9F_%D7%92%D7%91%D7%99%D7%A8',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 3,
    activityDate: '2023-04-02',
    activityType: 'budget_allocation',
    activityTitle: 'National Guard creation funding approved',
    description: 'Cabinet approved funding for Ben-Gvir\'s "National Guard" plan; creation of new armed force unit under ministry authority.',
    affectedPersonName: 'איתמר בן גביר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Armed forces, Security',
    notes: 'Proposed new paramilitary organization; controversial expansion of police-affiliated armed units.',
    hebrewNotes: 'אישור תקציב ליצירת משמר לאומי חדש',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 3,
    activityDate: '2024-01-15',
    activityType: 'reappointment',
    activityTitle: 'Ben-Gvir reappointed by cabinet despite AG objections',
    description: 'Cabinet unanimously reappointed Ben-Gvir as National Security Minister; Attorney General had filed objections regarding his fitness for office.',
    affectedPersonName: 'איתמר בן גביר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Political stability',
    notes: 'Cabinet override of AG concerns; indicates coalition commitment to Ben-Gvir despite controversies.',
    hebrewNotes: 'אישור מחדש של בן גביר למרות התנגדות יועץ המשפטי',
    dataSource: 'toi',
    sourceUrl: 'https://www.timesofisrael.com',
    confidenceLevel: 95,
  },

  // MINISTRY OF COMMUNICATIONS
  {
    canonicalOfficeId: 4, // communications
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Shlomo Karhi appointed Communications Minister',
    description: 'Shlomo Karhi (Likud) appointed as Minister of Communications; tasked with media regulation reform.',
    affectedPersonName: 'שלמה כרחי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Media, Communications',
    notes: 'Began work immediately on comprehensive media overhaul plans.',
    hebrewNotes: 'מינוי שר התקשורת חדש; התחזוקה של תכניות רפורמה דרמטיות',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%A9%D7%9C%D7%9E%D7%94_%D7%A7%D7%A8%D7%A2%D7%99',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 4,
    activityDate: '2023-07-25',
    activityType: 'reform',
    activityTitle: 'Broadcasting reform bill introduced',
    description: 'Karhi introduced comprehensive broadcasting reform bill; proposed shutdown of Second Authority for Television and Radio, creation of new single regulatory body with primarily political appointments.',
    affectedPersonName: 'שלמה כרחי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Media regulation, Broadcasting',
    notes: 'Radical restructuring of media governance; consolidation of regulatory authority under ministry control.',
    hebrewNotes: 'הצעה לרפורמה עמוקה בתחום השידורים; חיסול הרשות השנייה',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 4,
    activityDate: '2023-10-15',
    activityType: 'expansion',
    activityTitle: 'Emergency regulations for broadcast authority granted',
    description: 'Karhi proposed emergency regulations granting minister power to halt media broadcasts and confiscate equipment on "national security" grounds or claims of "enemy propaganda."',
    affectedPersonName: 'שלמה כרחי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Media control, Free speech',
    notes: 'Broad and vague emergency powers; raise significant press freedom concerns.',
    hebrewNotes: 'סמכויות חירום להשתקה של ערוצים בטענות ביטחון לאומי',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 90,
  },
  {
    canonicalOfficeId: 4,
    activityDate: '2023-10-20',
    activityType: 'controversy',
    activityTitle: 'Al Jazeera broadcasting ban proposed',
    description: 'Karhi initiated legislative action targeting Qatari news channel Al Jazeera; proposed ban on broadcasting from Israel.',
    affectedPersonName: 'שלמה כרחי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Foreign media, Press freedom',
    notes: 'Framed as national security measure but widely seen as political targeting of critical media outlet.',
    hebrewNotes: 'ניסיון להטיל אם על ערוץ אל ג\'זיזרה הקטרי',
    dataSource: 'jurist',
    sourceUrl: 'https://www.jurist.org',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 4,
    activityDate: '2023-11-23',
    activityType: 'controversy',
    activityTitle: 'Haaretz threatened with penalties over coverage',
    description: 'Karhi threatened Israeli daily Haaretz with government penalties for Gaza war coverage deemed unfavorable by the minister.',
    affectedPersonName: 'שלמה כרחי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Press freedom, Government control',
    notes: 'Direct attack on editorial independence; raises concerns about media pluralism and democratic norms.',
    hebrewNotes: 'איומים על עיתון הארץ על הסקת משנוע בשידורים',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 100,
  },

  // MINISTRY OF INTERIOR (Deri → Arbel transition)
  {
    canonicalOfficeId: 5, // interior
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Aryeh Deri appointed Interior Minister (with Health & Deputy PM)',
    description: 'Aryeh Deri (Shas) appointed to Interior, Health, and Deputy PM in unprecedented triple portfolio assignment.',
    affectedPersonName: 'אריה דרעי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Shas',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Interior, Coalition politics',
    notes: 'Controversial appointment due to Deri\'s legal history; triple ministry assignment unprecedented.',
    hebrewNotes: 'מינוי דרעי לשלוש תיקים; מינוי שנוי במחלוקת',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%90%D7%A8%D7%99%D7%94_%D7%93%D7%A8%D7%A2%D7%99',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 5,
    activityDate: '2023-01-18',
    activityType: 'legal_challenge',
    activityTitle: 'Supreme Court disqualifies Deri from ministerial service',
    description: 'Israel\'s Supreme Court ruled that Aryeh Deri is legally unfit to serve as minister due to tax fraud conviction; court cited breach of plea deal where Deri promised not to seek government office.',
    affectedPersonName: 'אריה דרעי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Shas',
    durationDays: 20,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Judicial oversight, Government fitness',
    notes: 'Court intervention in government composition; Deri served only 20 days.',
    hebrewNotes: 'בג"ץ הורה על הדחת דרעי בגלל עבר משפטי',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%90%D7%A8%D7%99%D7%94_%D7%93%D7%A8%D7%A2%D7%99',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 5,
    activityDate: '2023-01-24',
    activityType: 'dismissal',
    activityTitle: 'Deri dismissed; Moshe Arbel appointed Interior Minister',
    description: 'Following Supreme Court ruling, Deri was forced to resign. Moshe Arbel (Shas) appointed as replacement Interior Minister (also took Health portfolio).',
    affectedPersonName: 'משה ארבל',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Shas',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Interior administration',
    notes: 'Arbel took over Interior and Health from Deri; served until end of government tenure.',
    hebrewNotes: 'משה ארבל מונה בתחליפות; השתלטות על משרדים דרעי',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%A9%D7%94_%D7%90%D7%A8%D7%91%D7%9C',
    confidenceLevel: 100,
  },

  // MINISTRY OF FOREIGN AFFAIRS (Rotation: Katz → Cohen → Katz)
  {
    canonicalOfficeId: 6, // foreign affairs
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Israel Katz appointed Foreign Minister (first rotation)',
    description: 'Israel Katz (Likud) appointed Foreign Minister for first 2-year term under coalition rotation agreement with Eli Cohen.',
    affectedPersonName: 'ישראל כץ',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: 730,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Foreign policy, Diplomacy',
    notes: 'Pre-planned rotation agreement between Katz and Cohen; controversial timing changes during Gaza war.',
    hebrewNotes: 'כץ מונה בתחילת הממשלה כחלק מהסכם רוטציה',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%99%D7%A9%D7%A8%D7%90%D7%9C_%D7%9B%D7%A5',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 6,
    activityDate: '2024-01-01',
    activityType: 'rotation',
    activityTitle: 'Eli Cohen appointed Foreign Minister (rotation from Katz)',
    description: 'Eli Cohen (Likud) took over as Foreign Minister per pre-planned rotation agreement; Katz transferred to Energy Ministry.',
    affectedPersonName: 'אלי כהן',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: 730,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Foreign policy',
    notes: 'Planned rotation executed during active Gaza war; raised questions about diplomatic continuity.',
    hebrewNotes: 'כהן לוקח את המשרד מכץ במועד שוער בתקנון הקואליציה',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 100,
  },

  // MINISTRY OF EDUCATION
  {
    canonicalOfficeId: 7, // education
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Yoav Kisch appointed Education Minister',
    description: 'Yoav Kisch (Likud) appointed as Minister of Education; tasked with curriculum and examination reforms.',
    affectedPersonName: 'יואב קיש',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Education, Curriculum',
    notes: 'Began immediate review of previous government\'s education initiatives.',
    hebrewNotes: 'מינוי קיש לשר החינוך; התחזוקה של תכניות שינוי קריקולום',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%99%D7%95%D7%90%D7%91_%D7%A7%D7%99%D7%A9',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 7,
    activityDate: '2023-01-15',
    activityType: 'policy_reversal',
    activityTitle: 'Matriculation exam reforms cancelled',
    description: 'Kisch cancelled predecessor Yifat Shasha-Biton\'s matriculation reform; reversed elimination of written exams in humanities subjects.',
    affectedPersonName: 'יואב קיש',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Education assessment',
    notes: 'Replaced projects/multidisciplinary model with traditional written exam structure.',
    hebrewNotes: 'ביטול רפורמת הבחינות של שאשא-ביטון',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 7,
    activityDate: '2023-03-15',
    activityType: 'policy_launch',
    activityTitle: 'New matriculation framework announced',
    description: 'Kisch announced revised matriculation exam structure combining external exams (35%), project assignments (35%), and security mechanism (30%).',
    affectedPersonName: 'יואב קיש',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Education assessment',
    notes: 'Hybrid model balancing traditional and contemporary assessment methods.',
    hebrewNotes: 'מתווה חדש לבחינות הבגרות עם שילוב שיטות',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 90,
  },
  {
    canonicalOfficeId: 7,
    activityDate: '2023-06-15',
    activityType: 'curriculum',
    activityTitle: 'Jewish and Zionist studies curriculum expansion',
    description: 'Kisch unveiled sweeping expansion of Jewish and Zionist studies in school curriculum; made Bible study mandatory.',
    affectedPersonName: 'יואב קיש',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Curriculum, National identity',
    notes: 'Reflects government\'s emphasis on nationalist Jewish education; raises concerns from secular and Arab communities.',
    hebrewNotes: 'הרחבה משמעותית של לימודי יהדות וציונות',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 7,
    activityDate: '2023-11-15',
    activityType: 'curriculum',
    activityTitle: 'Democracy principles removed from matriculation exams',
    description: 'Ministry directive excised "principles of democracy" from matriculation exam content in humanities subjects.',
    affectedPersonName: 'יואב קיש',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'major',
    policyFocus: 'Curriculum, Democratic values',
    notes: 'Controversial removal; seen as ideological reorientation away from democratic principles in education.',
    hebrewNotes: 'הסרת עקרונות דמוקרטיה מחומר הלימוד בבחינות',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 90,
  },

  // MINISTRY OF STRATEGIC AFFAIRS (reopening)
  {
    canonicalOfficeId: 8, // strategic affairs
    activityDate: '2022-12-29',
    activityType: 'portfolio_transfer',
    activityTitle: 'Ministry of Strategic Affairs reopened',
    description: 'Ministry closed in August 2021 was reopened by new government; resurrection of strategic affairs portfolio under Ron Dermer.',
    affectedPersonName: 'רון דרמר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud (external appointment)',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Strategic planning',
    notes: 'Non-MK Dermer (former US ambassador) appointed to reconstituted ministry.',
    hebrewNotes: 'פתיחה מחדש של משרד שנסגר ב-2021',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%94%D7%9E%D7%A9%D7%A8%D7%93_%D7%9C%D7%A2%D7%A0%D7%99%D7%99%D7%A0%D7%99%D7%9D_%D7%90%D7%A1%D7%98%D7%A8%D7%98%D7%92%D7%99%D7%99%D7%9D',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 8,
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Ron Dermer appointed Minister of Strategic Affairs',
    description: 'Ron Dermer (non-MK, former US Ambassador) appointed to lead reopened Strategic Affairs Ministry; reports directly to Netanyahu.',
    affectedPersonName: 'רון דרמר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: null,
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Strategic planning, International relations',
    notes: 'Think-tank operational model; focus on Iran, Abraham Accords, Arab relations, US alliance.',
    hebrewNotes: 'דרמר מנוי לשר כשלא הוא חבר כנסת; דגם תנקיר',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 8,
    activityDate: '2023-01-15',
    activityType: 'personnel',
    activityTitle: 'Director General appointment attempt fails',
    description: 'Dermer attempted to appoint Jordana Cutler (Facebook executive) as Director General but appointment was not finalized; ministry continues without permanent DG.',
    affectedPersonName: 'רון דרמר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: null,
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Ministry administration',
    notes: 'Ministry operates without appointed director general; impacts operational capacity.',
    hebrewNotes: 'ניסיון מינוי מנכ"ל כושל; המשרד פועל בלי מנהל קבוע',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 85,
  },
  {
    canonicalOfficeId: 8,
    activityDate: '2023-02-15',
    activityType: 'controversy',
    activityTitle: 'Conflict of interest: 10% stake in polling institute',
    description: 'Reports reveal Dermer held 10% ownership stake in Mano Geva polling institute; raises conflict of interest concerns regarding political polling.',
    affectedPersonName: 'רון דרמר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: null,
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Ethics, Conflict of interest',
    notes: 'Undisclosed financial interest in political polling firm; governance concerns.',
    hebrewNotes: 'דרמר בעל שיעור במכון סקרים; שאלות אתיקה',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 85,
  },
  {
    canonicalOfficeId: 8,
    activityDate: '2026-03-15',
    activityType: 'expansion',
    activityTitle: 'Dermer expanded to handle Lebanon and US relations',
    description: 'Dermer given additional responsibilities to manage Lebanese government negotiations and serve as Netanyahu\'s point person with US administration.',
    affectedPersonName: 'רון דרמר',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: null,
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'International diplomacy',
    notes: 'Further centralization of foreign policy authority in Dermer; effectively a supraminister role.',
    hebrewNotes: 'הרחבת תפקידי דרמר לכללי אחריות על לבנון וארה"ב',
    dataSource: 'marker',
    sourceUrl: 'https://www.themarker.com',
    confidenceLevel: 80,
  },

  // MINISTRY OF HERITAGE (split from Jerusalem Affairs)
  {
    canonicalOfficeId: 9, // heritage
    activityDate: '2022-12-29',
    activityType: 'portfolio_transfer',
    activityTitle: 'Heritage split from Jerusalem Affairs',
    description: 'Coalition agreement provided for split of previously unified ministry; new "Ministry of Heritage" separated from "Ministry of Jerusalem & Tradition" to be held by UTJ.',
    affectedPersonName: 'עמיחי אליהו',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Portfolio distribution',
    notes: 'Coalition politics: Otzma Yehudit gets Heritage, United Torah Judaism gets Jerusalem & Tradition.',
    hebrewNotes: 'פיצול פורטפוליו בין שתי מפלגות קואליציוניות',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%A9%D7%A8%D7%93_%D7%94%D7%9E%D7%95%D7%A8%D7%A9%D7%AA',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 9,
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Amihai Eliyahu appointed Heritage Minister',
    description: 'Amihai Eliyahu (Jewish Power) appointed as Minister of Heritage; oversees cultural sites, archaeology, national heritage.',
    affectedPersonName: 'עמיחי אליהו',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Cultural heritage',
    notes: 'New ministry created as part of coalition arrangement.',
    hebrewNotes: 'אליהו מנוי לשר משרד חדש של מורשת',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 9,
    activityDate: '2023-01-29',
    activityType: 'portfolio_transfer',
    activityTitle: 'Israel Antiquities Authority transferred to Heritage Ministry',
    description: 'Israel Antiquities Authority transferred from Ministry of Culture to Ministry of Heritage; consolidates archaeological and heritage governance.',
    affectedPersonName: 'עמיחי אליהו',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Archaeology, Heritage management',
    notes: 'Functional consolidation of heritage-related authorities under single ministry.',
    hebrewNotes: 'העברת רשות העתיקות למשרד המורשת',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%A9%D7%A8%D7%93_%D7%94%D7%9E%D7%95%D7%A8%D7%A9%D7%AA',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 9,
    activityDate: '2023-06-15',
    activityType: 'budget_allocation',
    activityTitle: 'Heritage investment: 100+ million shekel allocation',
    description: 'Ministry invested over 100 million shekels in heritage site preservation, restoration, and tourism development around historical Jerusalem sites.',
    affectedPersonName: 'עמיחי אליהו',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: 100000000,
    controversyLevel: 'none',
    policyFocus: 'Heritage preservation, Tourism',
    notes: 'Significant funding reflects government priority on heritage development.',
    hebrewNotes: 'השקעה של מעל 100 מיליון שקל בשיקום אתרי מורשת',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 95,
  },
  {
    canonicalOfficeId: 9,
    activityDate: '2023-03-15',
    activityType: 'budget_allocation',
    activityTitle: 'Coalition funds: 72 million shekel allocation including 24M for Jewish heritage education',
    description: 'Government approved 72 million shekel coalition allocation to Heritage Ministry; 24 million earmarked specifically for Jewish heritage education initiatives.',
    affectedPersonName: 'עמיחי אליהו',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Jewish Power',
    durationDays: null,
    budgetAllocation: 72000000,
    controversyLevel: 'minor',
    policyFocus: 'Budget allocation, Education',
    notes: 'Coalition compensation: allocations to support coalition partner policy priorities.',
    hebrewNotes: 'הקצאת כספים קואליציוניים לתוכניות חינוך בעדכו של מורשת יהודית',
    dataSource: 'calcalist',
    sourceUrl: 'https://www.calcalist.co.il',
    confidenceLevel: 90,
  },

  // MINISTRY OF TRANSPORT
  {
    canonicalOfficeId: 10, // transport
    activityDate: '2022-12-29',
    activityType: 'appointment',
    activityTitle: 'Miri Regev reappointed Transport Minister (second tenure)',
    description: 'Miri Regev (Likud) reappointed as Minister of Transport and Road Safety; second term in this position.',
    affectedPersonName: 'מירי רגב',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Transport, Road safety',
    notes: 'Returning minister with continuity in transport policy.',
    hebrewNotes: 'רגב חוזרת למשרד התחבורה בתקופתה השנייה',
    dataSource: 'wikipedia-he',
    sourceUrl: 'https://he.wikipedia.org/wiki/%D7%9E%D7%99%D7%A8%D7%99_%D7%A8%D7%92%D7%91',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 10,
    activityDate: '2023-03-15',
    activityType: 'initiative',
    activityTitle: 'Autonomous vehicle technology program launched',
    description: 'Ministry initiated program promoting autonomous and self-driving vehicle technology; focus on smart road systems supervision.',
    affectedPersonName: 'מירי רגב',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Technology, Transportation',
    notes: 'Forward-looking tech initiative; includes Tesla autonomous trial in Israel.',
    hebrewNotes: 'התחזוקת תכנית כלים אוטונומיים; גם אוטובוסים חכמים',
    dataSource: 'ynet',
    sourceUrl: 'https://www.ynet.co.il',
    confidenceLevel: 85,
  },

  // DIASPORA AFFAIRS
  {
    canonicalOfficeId: 11, // diaspora
    activityDate: '2023-01-17',
    activityType: 'appointment',
    activityTitle: 'Amichay Chikli appointed Diaspora Affairs Minister',
    description: 'Amichay Chikli (Likud) appointed as Minister of Diaspora Affairs; resigned from Knesset to take position.',
    affectedPersonName: 'עמיחי שיקלי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Diaspora relations',
    notes: 'External appointment to ministry; took over from previous administration.',
    hebrewNotes: 'שיקלי מונה ויתכרע מהכנסת לתפקיד',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 11,
    activityDate: '2023-01-17',
    activityType: 'portfolio_transfer',
    activityTitle: 'Ministry expanded to include "Combating Antisemitism"',
    description: 'Ministry formally renamed from "Diaspora Affairs" to "Diaspora Affairs & Combating Antisemitism"; expanded mandate to international antisemitism efforts.',
    affectedPersonName: 'עמיחי שיקלי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Diaspora, Antisemitism',
    notes: 'Scope expansion reflects international antisemitism concerns post-October 7.',
    hebrewNotes: 'שינוי שם משרד לכללול פעילות למאבק בנוער אנטישמיות',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 100,
  },
  {
    canonicalOfficeId: 11,
    activityDate: '2023-10-07',
    activityType: 'role_expansion',
    activityTitle: 'Chikli takes lead on public diplomacy post-Oct 7',
    description: 'Following October 7 attack, Chikli\'s ministry took primary responsibility for international public diplomacy and communications efforts.',
    affectedPersonName: 'עמיחי שיקלי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'moderate',
    policyFocus: 'Public diplomacy, Communication',
    notes: 'Unnatural administrative arrangement; reflected vacuum in government communications post-attack.',
    hebrewNotes: 'שיקלי לקח אחריות על הסברה בינלאומית',
    dataSource: 'the7eye',
    sourceUrl: 'https://www.the7eye.org.il',
    confidenceLevel: 85,
  },
  {
    canonicalOfficeId: 11,
    activityDate: '2024-05-15',
    activityType: 'initiative',
    activityTitle: 'Diaspora Jewish murder memorialization program launched',
    description: 'Government approved Chikli\'s initiative to create memorial program for non-Israeli Jews murdered by antisemitic perpetrators.',
    affectedPersonName: 'עמיחי שיקלי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'none',
    policyFocus: 'Memorialization, Antisemitism',
    notes: 'New initiative to recognize diaspora victims of antisemitic violence.',
    hebrewNotes: 'תוכנית להנצחת יהודים בתפוצות שנהרגו בפגיעות אנטישמיות',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 85,
  },
  {
    canonicalOfficeId: 11,
    activityDate: '2024-08-01',
    activityType: 'initiative',
    activityTitle: '"Mashlat" antisemitism monitoring system launched',
    description: 'Ministry launched "Mashlat" (National Command Post) system to monitor and track online antisemitic discourse globally.',
    affectedPersonName: 'עמיחי שיקלי',
    affectedPersonId: null,
    governmentNum: 37,
    coalitionParty: 'Likud',
    durationDays: null,
    budgetAllocation: null,
    controversyLevel: 'minor',
    policyFocus: 'Antisemitism monitoring, Technology',
    notes: 'New monitoring infrastructure for international antisemitic content.',
    hebrewNotes: 'משלט - מערכת מעקב אחר דיון אנטישמי בעולם',
    dataSource: 'haaretz',
    sourceUrl: 'https://www.haaretz.com',
    confidenceLevel: 80,
  },
];

export function seedActivityJournal() {
  const db = new Database(DB_PATH);

  try {
    // Create table if not exists
    db.exec(`
      CREATE TABLE IF NOT EXISTS office_activity_journal (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        canonical_office_id INTEGER NOT NULL,
        activity_date TEXT NOT NULL,
        activity_type TEXT NOT NULL,
        activity_title TEXT NOT NULL,
        description TEXT NOT NULL,
        affected_person_name TEXT,
        affected_person_id INTEGER,
        government_num INTEGER,
        coalition_party TEXT,
        duration_days INTEGER,
        budget_allocation NUMERIC,
        controversy_level TEXT,
        policy_focus TEXT,
        notes TEXT,
        hebrew_notes TEXT,
        data_source TEXT,
        source_url TEXT,
        confidence_level INTEGER,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      );

      CREATE INDEX IF NOT EXISTS idx_office_activity_date
        ON office_activity_journal(canonical_office_id, activity_date);
      CREATE INDEX IF NOT EXISTS idx_activity_type
        ON office_activity_journal(activity_type);
      CREATE INDEX IF NOT EXISTS idx_controversy
        ON office_activity_journal(controversy_level);
    `);

    const insert = db.prepare(`
      INSERT INTO office_activity_journal (
        canonical_office_id, activity_date, activity_type, activity_title,
        description, affected_person_name, affected_person_id, government_num,
        coalition_party, duration_days, budget_allocation, controversy_level,
        policy_focus, notes, hebrew_notes, data_source, source_url, confidence_level
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    let inserted = 0;
    for (const activity of activities) {
      insert.run(
        activity.canonicalOfficeId,
        activity.activityDate,
        activity.activityType,
        activity.activityTitle,
        activity.description,
        activity.affectedPersonName,
        activity.affectedPersonId,
        activity.governmentNum,
        activity.coalitionParty,
        activity.durationDays,
        activity.budgetAllocation,
        activity.controversyLevel,
        activity.policyFocus,
        activity.notes,
        activity.hebrewNotes,
        activity.dataSource,
        activity.sourceUrl,
        activity.confidenceLevel,
      );
      inserted++;
    }

    console.log(`✅ Office Activity Journal seeded: ${inserted} entries inserted`);
    console.log('\nSample entries:');
    const samples = db.prepare(`
      SELECT activity_date, activity_title, affected_person_name, controversy_level
      FROM office_activity_journal
      ORDER BY activity_date DESC
      LIMIT 5
    `).all();

    for (const sample of samples as any[]) {
      console.log(`  ${sample.activity_date} | ${sample.activity_title} | ${sample.affected_person_name || 'N/A'} | ${sample.controversy_level}`);
    }
  } finally {
    db.close();
  }
}

seedActivityJournal();
